### ISSUE TITLE
readme: document `error.data` usage with `wrap`

### ISSUE THREAD

**Issue by tjmehta** [Runnable/error-cat#5]
Primarily of the purposes of documentation and making it easier to discover that `error.data` is a thing.
Thoughts?

**Comment by rsandor** [comment]
Primary concern I have is that it breaks direct compatibility with `Boom.wrap`.

**Comment by tjmehta** [comment]
Yup and I think I understand why:
https://github.com/hapijs/boom/blob/master/lib/index.js#L15

Not sure what we should do w/ data if `wrap` is passed a boom error.

**Comment by tjmehta** [comment]
In the case of `statusCode` the argument is ignored entirely if `wrap` is passed a boom error

**Comment by tjmehta** [comment]
An edgecase if a non-boom error already has a data property, what do we do with the data argument?

**Comment by tjmehta** [comment]
Maybe we just document that data should be set on an error before being passed to wrap in the readme.
That should be sufficient

**Comment by rsandor** [comment]
I think that's probably the best scenario, unless we want to rewrite the boom interface with out own tool (which seems like reinventing the wheel, tbh).
